image: cypress/base:18.16.0

pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - npm install
            - npm test
            - npm run e2e
  branches:
    master:
      - step:
          script:
            - npm install
            - npm run test
            - npm run e2e